spring:
  port: ${SPRING_PORT}
  application:
    name: CampusPark

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 15
      minimum-idle: 15

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hibernate.highlight_sql: true
        hibernate.session.events.log.LOG_QUERIES_SLOWER_THAN_MS: 100
  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.orm.jdbc.bind: trace
      org.hibernate.type.descriptor.sql: trace
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        base-url: ${OPENAI_BASE_URL}
        options:
          model: ${OPENAI_MODEL}
          temperature: ${OPENAI_TEMPERATURE}
          max-tokens: ${OPENAI_MAX_TOKENS}
        embedding:
          api-key: ${OPENAI_API_KEY}

        completions-path: "/chat/completions"

kakao:
  api:
    key: ${KAKAO_API_KEY}

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    s3:
      bucket: ${S3_BUCKET_NAME}
    region:
      region-value: ap-northeast-2
